language: ruby

branches:
  only:
    - master

rvm:
  - 2.6.3

cache: bundler

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

before_script:
  - chmod +x ./script/cibuild

script: ./script/cibuild
exclude: [vendor]
sudo: false