# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: thinkaliker
email: adam@thinkaliker.com
description: > # this means to ignore newlines until "baseurl:"
  thinkaliker / Adam Chao
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thinkaliker.com" # the base hostname & protocol for your site
twitter_username: thinkaliker
github_username:  thinkaliker

# Build settings
markdown: kramdown

#other settings
#pagination: 5
#paginate_path: "/blog/page:num/"
#gems: [jekyll-paginate]
